[package]
name = "rust_frame_grabber"
version = "0.1.0"
authors = ["Alan Mantoux <alan.mantoux@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
